version: '3.1'

services:
  db:
    image: postgres:11.5-alpine
    hostname: app-db
    environment:
      POSTGRES_PASSWORD: 123123qa
      POSTGRES_USER: app
      POSTGRES_DB: warehouse

  queue:
    image: rabbitmq:3.7.17-management-alpine
    hostname: app-rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1      

  search: 
    image: elasticsearch:7.3.0
    hostname: elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9200"]
      interval: 5s
      timeout: 15s
      retries: 1             

  kibana:
    image: kibana:7.3.0
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://search:9200
    ports:
      - 5601:5601  

  app:
    depends_on:
      - db
      - search
      - queue
    build: .
    hostname: dapp
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_URL: http://search:9200
      RABBITMQ_HOSTNAME: queue
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      POSTGRES_HOSTNAME: db
      POSTGRES_PASSWORD: 123123qa
      POSTGRES_USER: app
      POSTGRES_DB: warehouse